export const PETS = [
    {name: "Dog", value: "DOG", image: require('../assets/images/Pets/Dog.png')},
    {name: "Cat", value: "CAT", image: require('../assets/images/Pets/Cat.png')},
    {name: "Bird", value: "BIRD", image: require('../assets/images/Pets/Bird.png')},
    {name: "Fish", value: "FISH", image: require('../assets/images/Pets/Fish.png')},
    {name: "Hamster", value: "HAMSTER", image: require('../assets/images/Pets/Hamster.png')},
    {name: "Rabbit", value: "RABBIT", image: require('../assets/images/Pets/Rabbit.png')},
    {name: "Turtle", value: "TURTLE", image: require('../assets/images/Pets/Turtle.png')},
    {name: "Lizard", value: "LIZARD", image: require('../assets/images/Pets/Lizard.png')},
    // {name: "Ferret", value: "FERRET", image: require('../assets/images/Pets/Ferret.png')},
    // {name: "Snake", value: "SNAKE", image: require('../assets/images/Pets/Snake.png')},
    // {name: "Guinea Pig", value: "GUINEA_PIG", image: require('../assets/images/Pets/Guinea Pig.png')},
    // {name: "Chinchilla", value: "CHINCHILLA", image: require('../assets/images/Pets/Chinchilla.png')},
    // {name: "Gerbil", value: "GERBIL", image: require('../assets/images/Pets/Gerbil.png')},
    // {name: "Rat", value: "RAT", image: require('../assets/images/Pets/Rat.png')},
    // {name: "Hedgehog", value: "HEDGEHOG", image: require('../assets/images/Pets/Hedgehog.png')},
    // {name: "Hermit Crab", value: "HERMIT_CRAB", image: require('../assets/images/Pets/Hermit Crab.png')},
    // {name: "Sugar Glider", value: "SUGAR_GLIDER", image: require('../assets/images/Pets/Sugar Glider.png')},
];